services:
  - type: web
    name: codesye-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health 